spring:
  application:
    name: products-api
  data:
    mongodb:
      auto-index-creation: true
      uri: "mongodb+srv://${atlas.username}:${atlas.pwd}@${atlas.cluster}/${atlas.dbname}?retryWrites=true"

atlas:
  username: "encryptedusername"
  pwd: "encryptedpwd"
  cluster: "theatlascluster"
  dbname: "thedatabasename"

server:
  port: ${PORT}

eureka:
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"